ALTER TABLE riders
  ADD COLUMN IF NOT EXISTS id_number VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS id_issue_date DATE NULL,
  ADD COLUMN IF NOT EXISTS id_expiry_date DATE NULL,
  ADD COLUMN IF NOT EXISTS nuit VARCHAR(40) NULL,
  ADD COLUMN IF NOT EXISTS address_line VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS bi_front_path VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS bi_back_path VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS selfie_path VARCHAR(255) NULL;
